### ISSUE TITLE
set root directorty

### ISSUE THREAD

**Issue by SkyJedi** [kerphi/phpfreechat#30]
could we get ability to add this to a subdirectory (mysite/chat/) instead of unzipping to the root folder of your Web server. (mysite/)?

**Comment by justhankmoody** [comment]
Hi.
Need set **serverUrl [String:'../server']**  parameter 
```javascript
$('#mychat').phpfreechat({
  refresh_delay: 2000,
  serverUrl: ",mysite/chat-path/server"
  focus_on_connect: false
});
```
